#!/bin/bash
cat<<EOF
      _=_      
    q(-_-)p    
    '_) (_`    
    /__/  \    
  _(<_   / )_  
 (__\_\_|_/__) 

EOF
for i in {16..21} {21..16} ; do echo -en "\e[48;5;${i}m \e[0m" ; done ; echo

